### ISSUE TITLE
Cannot use input type number.

### ISSUE THREAD

**Issue by tsara27** [EmKayDK/jstepper#1]
If I use input type number.
<input type="number"/>
I can use the min and max feature but when I type alphabet, it doesn't work.

**Comment by goddamnyouryan** [comment]
@EmKayDK Just out of curiosity, has there been any progress on this? I agree with @jedierikb it would be great for touch devices.

**Comment by EmKayDK** [comment]
There has not been any progress on this yet, but I will get to it eventually :)
Sorry to keep you waiting.

**Comment by EmKayDK** [comment]
I have investigated this and decided not to bring support for the number input field.
It is too intrusive and conflicts with the default functionality and the event handling of the stepping in a number field is also quite different compared to a "normal" text field.

However, there are numerous solutions for creating a number field for a touch device and a normal jStepper text field on a regular computer:

Here is one (untested pseudo code):
```javascript
if (IsTouchDevice()) {
    $('#fieldId').attr('type', 'number');
} else {
    $('#fieldId').jStepper();
}
```

There are several ways to detect if it is a touch device. Here is a nice StackOverflow question where a lot of the ways are discussed: http://stackoverflow.com/questions/4817029
