### ISSUE TITLE
Dashes are not excluded

### ISSUE THREAD

**Issue by ngocdiepnguyen** [EmKayDK/jstepper#13]
Hello!

I'm about to apply your plugin to my project but I found an issue that if I input some  number and then input many dashes then the dashes still remain in the text field. (Ex: 54--------------53453).

The snippet of code I am using is:
$('#MaxEntries').jStepper({ minValue: 1, minLength: 1, allowDecimals: false, disableNonNumeric: true });

Please investigate and fix it.

Thanks and best regards,
Diane

**Comment by EmKayDK** [comment]
Thank you for the bug report.
This issue has now been fixed.
