### ISSUE TITLE
not changing the minValue and maxValue when reinitiating on the same element

### ISSUE THREAD

**Issue by haruhinoshana** [EmKayDK/jstepper#21]
hi everyone

im using this plugin but there a bug when i reinitialize it on the same id it will not get my new 
minValue and maxValue

here my code

	$("#empid0").on('change',function(){
	var td_count = $(this).attr("cnt");
  	//var tempid=$(this).attr("tempid");
  	//var empno=$("#empid"+td_count+" option:selected").attr("cc");
  	var empname=$("#empid"+td_count+" option:selected").attr("e_name");
  	var company_code=$("#empid"+td_count+" option:selected").attr("cc");
  	var branch_code=$("#empid"+td_count+" option:selected").attr("bc");	

	  //
      //$("#empid"+td_count).val(empno);
      $("#empname"+td_count).val(empname);
      $("#empname"+td_count).attr("title",empname);
      $("#cc"+td_count).val(company_code);
      $("#bc"+td_count).val(branch_code);		
	});

	//element menu append to element name etc..
	$("#element_name0").on('change',function(){
	  //console.log("sss");
  	  var td_count =$(this).attr('cnt'); 		
      var treid=$("#element_name"+td_count+" option:selected").attr("element-id");
      var is_special=$("#element_name"+td_count+" option:selected").attr("is_special");
      var etxt=$(this).val();
      //alert("1");
      //var etypetxt=$(this).attr("element_menu_type");
      //alert(etxt +" || "+ etypetxt + "||" + treid);
      
      ///////////////////////////////////////
      //insert initial data on main table. //
      ///////////////////////////////////////
      
      //$("#element_name"+td_count).val(etxt).trigger('change');
      $("#element_name"+td_count).attr("title",etxt);
      $("#element_name"+td_count).attr("element-id",treid);

      $("#element_id"+td_count).val(treid);
      $("#element-btn"+td_count).attr("element-id",treid);
	  $( "#element-sbtn"+td_count ).attr("element-id",treid);      
      //$("#type"+td_count).val(etypetxt);

      //alert(etxt);
      //return false;
      if(is_special=="1"){
        showEntryModalValuesException(td_count,etxt,treid);
      } else {
        showEntryModalValues(td_count,etxt,treid);
      }		
	});

function showEntryModalValues(count,text,teid){
        var count = count;//$(button).attr('cnt');
        $.ajax({
          url: base_url+"/entry_modal",
          type: 'POST',
          dataType: 'json',
          data: {
            element_id: teid,
            element_name : text,
          },
          headers: {
            'X-CSRF-TOKEN': $("#token").val(),
          },
          beforeSend: function(data){
          loader.showPleaseWait();
          //reset values....
          $("#amount"+count).val("");
          $("#amount"+count).attr('readonly',true); 
          $("#hours"+count).val("");
          $("#hours"+count).attr('readonly',true);   
          $("#days"+count).val("");
          $("#days"+count).attr('readonly',true);  
          $("#adjustment_date"+count).val("");
          $("#element_label"+count).val(""); 

          for ( var i = 0, l = 13; i <= l; i++ ) {
               $("element-ent"+i+"-"+count).val("");
          } 
          //$("#adjustment_date"+count).attr('readonly',true);          
          //$("#adjustment_date"+count).removeClass('adjustment_date');
          //$("#adjustment_date"+count).bootstrapDP("remove");                        
          },          
          complete: function(data) {
            //called when complete
            loader.hidePleaseWait();
          },
          success: function(response) {
            //console.log(response);
            // /data = jQuery.parseJSON(data);
            
            if(response.data!=''){
              //$.each(data,function(index,value){
                $.each(response.data,function(index1,value1){
                   //process fields base on count and values return....
                   //console.log(value1);
                   if(value1.base_name=="Pay Value" && value1.user_enterable_flag=='Y'){
                      $("#amount"+count).val();
                      $("#element_label"+count).val(value1.base_name);
                      $("#amount"+count).attr('readonly',false);  

                      if(value1.min=='' || value1.min==null) { value1.min=0 } else { value1.min=parseInt(value1.min) }
                      if(value1.max=='' || value1.max==null) { value1.max=0 } else { value1.max=parseInt(value1.max) }

                      $("#amount"+count).jStepper({
                          minValue:value1.min, 
                          maxValue:value1.max, 
                          //defaultValue:0,
                          allowDecimals:true,
                          minDecimals:2,
                          maxDecimals:2,
                        });
                   } else if(value1.base_name=="Amount" && value1.user_enterable_flag=='Y'){
                      $("#amount"+count).val();
                      $("#element_label"+count).val(value1.base_name);
                      $("#amount"+count).attr('readonly',false);  

                      if(value1.min=='' || value1.min==null) { value1.min=0 } else { value1.min=parseInt(value1.min) }
                      if(value1.max=='' || value1.max==null) { value1.max=0 } else { value1.max=parseInt(value1.max) }

                      $("#amount"+count).jStepper({
                          minValue:value1.min, 
                          maxValue:value1.max, 
                          //defaultValue:0,
                          allowDecimals:true,
                          minDecimals:2,
                          maxDecimals:2,
                        });
                   } else if(value1.base_name=="Hours" && value1.user_enterable_flag=='Y'){
                      $("#hours"+count).val();
                      $("#hours"+count).attr('readonly',false);

                      if(value1.min=='' || value1.min==null) { value1.min=0} else { }//value1.min=parseFloat(value1.min) }
                      if(value1.max=='' || value1.max==null) { value1.max=0 } else { }//value1.max=parseFloat(value1.max) }
                        //alert(value1.min+" X "+value1.max);
                      $("#hours"+count).jStepper({
                          minValue:value1.min, 
                          maxValue:value1.max, 
                          allowDecimals:true,                          
                          //defaultValue:0,
                          //overflowMode:'ignore',
                          minDecimals:2,
                          maxDecimals:2,
                        });
                   } else if(value1.base_name=="Days" && value1.user_enterable_flag=='Y'){
                      $("#days"+count).val();
                      $("#days"+count).attr('readonly',false);

                      if(value1.min=='' || value1.min==null) { value1.min=0 } else { value1.min=parseInt(value1.min) }
                      if(value1.max=='' || value1.max==null) { value1.max=0 } else { value1.max=parseInt(value1.max) }
                        //alert(value1.min+" XXX "+value1.max);
/*                      $("#days"+count).removeAttr("id");
                      $("#days"+count).removeAttr("id","days"+count);  */                    
                      $("#days"+count).jStepper({
                          minValue:value1.min, 
                          maxValue:value1.max, 
                          //defaultValue:0,
                          //overflowMode:'ignore',
                          //minDecimals:2
                        });

                   } else if(value1.base_name=="Effective Date" && value1.user_enterable_flag=='Y'){
                      $("#effective_date"+count).val();
                      $("#effective_date"+count).attr('readonly',false);
                      //$("#adjustment_date"+count).addClass('adjustment_date');
                      $("#effective_date"+count).bootstrapDP({
                      format: "mm/dd/yyyy",
                      //viewMode: "months", 
                      //minViewMode: "months"
                      });
                   }

                });
            //});
            }
            hideModal("large");
/*            hideModal("large");
            showModal("medium",data);
            $("#modal-entry-back").attr("entry-count",count);*/
          },
          error: function(data) {
            // called when there is an error....
            loader.hidePleaseWait();
            hideModal("large");
          }
        });
}

**Comment by EmKayDK** [comment]
You shouldn't initialize jStepper more than once on any element.
If you want to change some settings for a jStepper instance you can simply overwrite that setting.

Please look at the documentation for this on http://jstepper.emkay.dk/. (It is located below the list of options under the header "Setting options after initialization").

In your case it should be something like this:
$("#days"+count).jStepper('option', 'minValue', value1.min);

If it's possible you could move the initializing of jStepper on the fields out of your onChange event handler and then only change the relevant options inside your onChange event handler.

Another way could be to somehow tag each field after jStepper is initialized and then in later iterations check on this tagging to be able to see if you should initialize jStepper on the field or just change the relevant options.
I am considering adding a new option for jStepper to make this a bit easier, but until then you have to do this part manually.

**Comment by haruhinoshana** [comment]
sir thank you for the quick reply, I would do it as you suggested .
