### ISSUE TITLE
onStep is not working at all

### ISSUE THREAD

**Issue by BjornMelgaard** [EmKayDK/jstepper#26]
try paste code below in stript field here http://jstepper.emkay.dk/ and test it  

```
$('#txtTesting').jStepper({minValue:0, maxValue:23, minLength:2, onStep: testfunction});

function testfunction(objTextField, bDirection, bLimitReached) {

  if (bDirection) {
    // Was increased
  } else {
    // Was decreased
  }
  if (bLimitReached) {
    // A limit was reached
  } else {
    // A limit was not reached
  }

  alert(objTextField.val());

}

```

**Comment by EmKayDK** [comment]
I have just tried it and it works fine. 

Have you pressed the "Apply" button after inserting the script?
What behaviour are you seeing? 
Is there an error in the console?

**Comment by BjornMelgaard** [comment]
@EmKayDK fk, I got it, its only working when using up and down keys, sorry, I was entering values by hand and was waiting for something to happen.
