### ISSUE TITLE
dynamically change values

### ISSUE THREAD

**Issue by jedierikb** [EmKayDK/jstepper#5]
Can I dynamically change the min and max values after instantiation?  Could you provide an example?

**Comment by EmKayDK** [comment]
It is not yet possible to change the options after instantiation. It is, however, one of the features planned for the plugin, so you will have the opportunity very soon.

**Comment by EmKayDK** [comment]
This is now possible with the 1.5.0 release.
Take a look at the documentation at http://jstepper.emkay.dk/.

Thanks again :+1:
