### ISSUE TITLE
dash character not excluded

### ISSUE THREAD

**Issue by inexuscore** [EmKayDK/jstepper#9]
Hello

I came across your website today and thought it's a good plugin for my purposes. one thing though, if you type a dash (-) character it will be excluded after keyPress, but if you input some digits and **then** input a dash character, it will remain in the input field.
Maybe I'm using it wrong, if so please point out my mistake. If this is a bug, I would appreciate it being fixed in the next release.

Thanks in advance

**Comment by EmKayDK** [comment]
Hi!

Thank you for your message and your observation.

Could you provide a more detailed description on how to reproduce the bug?
For example, which options do you use for the plugin and which steps do you take to get an error?

Thanks in advance

M

**Comment by inexuscore** [comment]
Hello
Thank you for your message and quick reply.
Sure thing, I have a working sample at the office, I'll try to email you a
working copy tomorrow before noon.

Thank you
A

On Tue, Jan 27, 2015 at 9:38 PM, Martin Kruse <notifications@github.com>
wrote:

> Hi!
>
> Thank you for your message and your observation.
>
> Could you provide a more detailed description on how to reproduce the bug?
> For example, which options do you use for the plugin and which steps do
> you take to get an error?
>
> Thanks in advance
>
> M
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmKayDK/jstepper/issues/9#issuecomment-71696891>.
>



-- 

*[ think twice, think algorithmic ] [:[ i , nexus ] [ pragmatic chaos ] [:*

**Comment by EmKayDK** [comment]
Any news on this? :)

**Comment by inexuscore** [comment]
Hi!
Sorry i got busy and totally forgot about this. consider this example:
'''javascript
$(document).ready(function() {
  $("input#myValue").jStepper({
    minValue: 1,
    allowDecimals: false
  });
});
'''
After initializing the plugin with this configuration everything works fine, except for when you input a hyphen character. For instance, if you type **123** then **-** then **456** the hyphen character remains in the input field. Is this behavior correct, am I missing something here?

Thanks again for your time :)

**Comment by EmKayDK** [comment]
I just uploaded a bug fix for this. I made it so dashes are just ignored if they are not typed as the first character in the field.

**Comment by inexuscore** [comment]
Hello Martin
Thank you for your time and this fix, i appreciate it.

Best Regards

On Mon, May 4, 2015 at 2:00 PM, Martin Kruse <notifications@github.com>
wrote:

> I just uploaded a bug fix for this. I made it so dashes are just ignored
> if they are not typed as the first character in the field.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmKayDK/jstepper/issues/9#issuecomment-98649681>.
>



-- 

*[ think twice, think algorithmic ] [:[ i , nexus ] [ pragmatic chaos ] [:*
